# Stage 1: Builder
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Runner
FROM nginx:alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html
# Note: In production we use docker-compose to mount the nginx spa config
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
