name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    - name: Install dependencies (Backend)
      run: cd backend && npm ci

    - name: Generate Prisma Types
      run: cd backend && npx prisma generate

    - name: Run Backend Tests
      run: cd backend && npx vitest run

    - name: Install dependencies (Frontend)
      run: cd frontend && npm ci

    - name: Run Frontend Tests
      run: cd frontend && npx vitest run
